name: hdf5_manager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nicegui
  - h5py
  - pandas
  - openpyxl
  - numpy
  - pytest
  - pygobject  # [linux]
  - pip:
    - "pywebview[qt]"
